<a href="https://colab.research.google.com/github/hyeonniii/NLP/blob/main/_Pandas_%ED%95%9C%EB%B2%88%EC%97%90_%EC%A0%9C%EB%8C%80%EB%A1%9C_%EB%B0%B0%EC%9A%B0%EA%B8%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas 한번에 제대로 배우기




---



In [3]:
import numpy as np
import pandas as pd
pd.__version__

'1.3.5'

## Pandas 객체


### Series 객체

In [4]:
s = pd.Series([0,0.25,0.5,0.75,1.0])
s

0    0.00
1    0.25
2    0.50
3    0.75
4    1.00
dtype: float64

In [5]:
s.values

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [6]:
s.index

RangeIndex(start=0, stop=5, step=1)

In [7]:
s[1]

0.25

In [8]:
s[1:4]

1    0.25
2    0.50
3    0.75
dtype: float64

In [9]:
s = pd.Series([0,0.25,0.5,0.75,1.0], index = ['a','b','c','d','e'])
s


a    0.00
b    0.25
c    0.50
d    0.75
e    1.00
dtype: float64

In [10]:
s['c']

0.5

In [11]:
s[['c','d','e']]

c    0.50
d    0.75
e    1.00
dtype: float64

In [12]:
'b' in s

True

In [13]:
s = pd.Series([0,0.25,0.5,0.75,1.0],index=[2,4,6,8,10])
s

2     0.00
4     0.25
6     0.50
8     0.75
10    1.00
dtype: float64

In [14]:
s[4]

0.25

In [15]:
s[2:]

6     0.50
8     0.75
10    1.00
dtype: float64

In [16]:
s.unique()

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [17]:
s.value_counts()

0.00    1
0.25    1
0.50    1
0.75    1
1.00    1
dtype: int64

In [18]:
s.isin([0.25, 0.75])

2     False
4      True
6     False
8      True
10    False
dtype: bool

In [19]:
pop_tuple = {'서울특별시':9728846,'부산광역시':3404423,'인천광역시':2947217,'대구광역시':2427954,'대전광역시':1471640,'광주광역시':1455048}
population = pd.Series(pop_tuple)
population

서울특별시    9728846
부산광역시    3404423
인천광역시    2947217
대구광역시    2427954
대전광역시    1471640
광주광역시    1455048
dtype: int64

In [20]:
population['서울특별시']

9728846

In [21]:
population['서울특별시':'인천광역시']

서울특별시    9728846
부산광역시    3404423
인천광역시    2947217
dtype: int64

### DataFrame 객체

In [22]:
pd.DataFrame([{'A':2,'B':4,'D':3},{'A':4,'B':5,'C':7}])

A  B    D    C
0  2  4  3.0  NaN
1  4  5  NaN  7.0

In [23]:
pd.DataFrame(np.random.rand(5,5),columns=['A','B','C','D','E'], index=[1,2,3,4,5])

A         B         C         D         E
1  0.228065  0.842615  0.810666  0.388810  0.049593
2  0.832232  0.246914  0.141539  0.655399  0.764976
3  0.217982  0.164307  0.193398  0.438492  0.917936
4  0.420967  0.764868  0.256864  0.744375  0.016274
5  0.569441  0.821254  0.341395  0.514631  0.720173

In [24]:
male_tuple = {'서울특별시':4732275,'부산광역시':1668618,'인천광역시':1476813,'대구광역시':1198815,'대전광역시':734441,'광주광역시':720060}
male = pd.Series(male_tuple)
male

서울특별시    4732275
부산광역시    1668618
인천광역시    1476813
대구광역시    1198815
대전광역시     734441
광주광역시     720060
dtype: int64

In [25]:
female_tuple = {'서울특별시':4988571,'부산광역시':1735805,'인천광역시':1470404,'대구광역시':1229139,'대전광역시':736599,'광주광역시':734988}
female = pd.Series(female_tuple)
female

서울특별시    4988571
부산광역시    1735805
인천광역시    1470404
대구광역시    1229139
대전광역시     736599
광주광역시     734988
dtype: int64

In [26]:
korea_df = pd.DataFrame({'인구수':population,'남자인구수':male,'여자인구수':female})
korea_df

인구수    남자인구수    여자인구수
서울특별시  9728846  4732275  4988571
부산광역시  3404423  1668618  1735805
인천광역시  2947217  1476813  1470404
대구광역시  2427954  1198815  1229139
대전광역시  1471640   734441   736599
광주광역시  1455048   720060   734988

In [27]:
korea_df.index

Index(['서울특별시', '부산광역시', '인천광역시', '대구광역시', '대전광역시', '광주광역시'], dtype='object')

In [28]:
korea_df.columns

Index(['인구수', '남자인구수', '여자인구수'], dtype='object')

In [29]:
korea_df['여자인구수']

서울특별시    4988571
부산광역시    1735805
인천광역시    1470404
대구광역시    1229139
대전광역시     736599
광주광역시     734988
Name: 여자인구수, dtype: int64

In [30]:
korea_df['서울특별시':'인천광역시']

인구수    남자인구수    여자인구수
서울특별시  9728846  4732275  4988571
부산광역시  3404423  1668618  1735805
인천광역시  2947217  1476813  1470404

### Index 객체


In [31]:
idx = pd.Index([2,4,6,8,10])
idx

Int64Index([2, 4, 6, 8, 10], dtype='int64')

In [32]:
idx[1]

4

In [33]:
idx[1:2:2]

Int64Index([4], dtype='int64')

In [34]:
idx[-1::]

Int64Index([10], dtype='int64')

In [35]:
idx[::2]

Int64Index([2, 6, 10], dtype='int64')

In [36]:
print(idx)
print(idx.size)
print(idx.shape)
print(idx.ndim)
print(idx.dtype)

Int64Index([2, 4, 6, 8, 10], dtype='int64')
5
(5,)
1
int64


#### Index 연산

In [37]:
idx1 = pd.Index([1,2,4,6,8])
idx2 = pd.Index([2,4,5,6,7])
print(idx1.append(idx2))
print(idx1.difference(idx2)) # 차집합
print(idx1 - idx2)
print(idx1.intersection(idx2))
print(idx1 & idx2)
print(idx1.union(idx2))
print(idx1 | idx2)
print(idx1.delete(0))
print(idx1.drop(1))
print(idx1 ^ idx2) # 여집합

Int64Index([1, 2, 4, 6, 8, 2, 4, 5, 6, 7], dtype='int64')
Int64Index([1, 8], dtype='int64')
Int64Index([-1, -2, -1, 0, 1], dtype='int64')
Int64Index([2, 4, 6], dtype='int64')
Int64Index([2, 4, 6], dtype='int64')
Int64Index([1, 2, 4, 5, 6, 7, 8], dtype='int64')
Int64Index([1, 2, 4, 5, 6, 7, 8], dtype='int64')
Int64Index([2, 4, 6, 8], dtype='int64')
Int64Index([2, 4, 6, 8], dtype='int64')
Int64Index([1, 5, 7, 8], dtype='int64')


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: FutureWarning: Index.__and__ operating as a set operation is deprecated, in the future this will be a logical operation matching Series.__and__.  Use index.intersection(other) instead
  import sys
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: FutureWarning: Index.__or__ operating as a set operation is deprecated, in the future this will be a logical operation matching Series.__or__.  Use index.union(other) instead
  if __name__ == '__main__':
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:12: FutureWarning: Index.__xor__ operating as a set operation is deprecated, in the future this will be a logical operation matching Series.__xor__.  Use index.symmetric_difference(other) instead
  if sys.path[0] == '':




---



## 인덱싱(Indexing)

In [38]:
s = pd.Series([0,0.25,0.5,0.75,1.0],index = ['a','b','c','d','e'])
s

a    0.00
b    0.25
c    0.50
d    0.75
e    1.00
dtype: float64

In [39]:
'b' in s

True

In [40]:
s['b']

0.25

In [41]:
s.keys()

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [42]:
list(s.items())

[('a', 0.0), ('b', 0.25), ('c', 0.5), ('d', 0.75), ('e', 1.0)]

In [43]:
s['f']=1.25
s

a    0.00
b    0.25
c    0.50
d    0.75
e    1.00
f    1.25
dtype: float64

In [44]:
s['a':'d']

a    0.00
b    0.25
c    0.50
d    0.75
dtype: float64

In [45]:
s[0:4]

a    0.00
b    0.25
c    0.50
d    0.75
dtype: float64

In [46]:
s[(s>0.4)&(s<0.8)]

c    0.50
d    0.75
dtype: float64

In [47]:
s[['a','c','e']]

a    0.0
c    0.5
e    1.0
dtype: float64

### Series 인덱싱

In [48]:
s=pd.Series(['a','b','c','d','e'],index=[1,3,5,7,9])
s

1    a
3    b
5    c
7    d
9    e
dtype: object

In [49]:
s[1]

'a'

In [50]:
s[2:4]

5    c
7    d
dtype: object

In [51]:
s.iloc[1]

'b'

In [52]:
s.iloc[2:4]

5    c
7    d
dtype: object

In [53]:
s.reindex(range(10))

0    NaN
1      a
2    NaN
3      b
4    NaN
5      c
6    NaN
7      d
8    NaN
9      e
dtype: object

In [54]:
s.reindex(range(10),method='bfill')

0    a
1    a
2    b
3    b
4    c
5    c
6    d
7    d
8    e
9    e
dtype: object

### DataFrame 인덱싱


In [55]:
korea_df

인구수    남자인구수    여자인구수
서울특별시  9728846  4732275  4988571
부산광역시  3404423  1668618  1735805
인천광역시  2947217  1476813  1470404
대구광역시  2427954  1198815  1229139
대전광역시  1471640   734441   736599
광주광역시  1455048   720060   734988

In [56]:
korea_df['남자인구수']

서울특별시    4732275
부산광역시    1668618
인천광역시    1476813
대구광역시    1198815
대전광역시     734441
광주광역시     720060
Name: 남자인구수, dtype: int64

In [57]:
korea_df.남자인구수

서울특별시    4732275
부산광역시    1668618
인천광역시    1476813
대구광역시    1198815
대전광역시     734441
광주광역시     720060
Name: 남자인구수, dtype: int64

In [58]:
korea_df.여자인구수

서울특별시    4988571
부산광역시    1735805
인천광역시    1470404
대구광역시    1229139
대전광역시     736599
광주광역시     734988
Name: 여자인구수, dtype: int64

In [59]:
korea_df['남여비율'] = (korea_df['남자인구수']*100/korea_df['여자인구수'])

In [60]:
korea_df.남여비율

서울특별시     94.862336
부산광역시     96.129346
인천광역시    100.435867
대구광역시     97.532907
대전광역시     99.707032
광주광역시     97.968946
Name: 남여비율, dtype: float64

In [61]:
korea_df.values

array([[9.72884600e+06, 4.73227500e+06, 4.98857100e+06, 9.48623363e+01],
       [3.40442300e+06, 1.66861800e+06, 1.73580500e+06, 9.61293463e+01],
       [2.94721700e+06, 1.47681300e+06, 1.47040400e+06, 1.00435867e+02],
       [2.42795400e+06, 1.19881500e+06, 1.22913900e+06, 9.75329072e+01],
       [1.47164000e+06, 7.34441000e+05, 7.36599000e+05, 9.97070319e+01],
       [1.45504800e+06, 7.20060000e+05, 7.34988000e+05, 9.79689464e+01]])

In [62]:
korea_df.T

서울특별시         부산광역시         인천광역시         대구광역시         대전광역시  \
인구수    9.728846e+06  3.404423e+06  2.947217e+06  2.427954e+06  1.471640e+06   
남자인구수  4.732275e+06  1.668618e+06  1.476813e+06  1.198815e+06  7.344410e+05   
여자인구수  4.988571e+06  1.735805e+06  1.470404e+06  1.229139e+06  7.365990e+05   
남여비율   9.486234e+01  9.612935e+01  1.004359e+02  9.753291e+01  9.970703e+01   

              광주광역시  
인구수    1.455048e+06  
남자인구수  7.200600e+05  
여자인구수  7.349880e+05  
남여비율   9.796895e+01

In [63]:
korea_df.values[0]

array([9.72884600e+06, 4.73227500e+06, 4.98857100e+06, 9.48623363e+01])

In [64]:
korea_df['인구수']

서울특별시    9728846
부산광역시    3404423
인천광역시    2947217
대구광역시    2427954
대전광역시    1471640
광주광역시    1455048
Name: 인구수, dtype: int64

In [65]:
korea_df.loc[:'인천광역시',:'남자인구수']

인구수    남자인구수
서울특별시  9728846  4732275
부산광역시  3404423  1668618
인천광역시  2947217  1476813

In [66]:
korea_df.loc[(korea_df.여자인구수 > 1000000)]

인구수    남자인구수    여자인구수        남여비율
서울특별시  9728846  4732275  4988571   94.862336
부산광역시  3404423  1668618  1735805   96.129346
인천광역시  2947217  1476813  1470404  100.435867
대구광역시  2427954  1198815  1229139   97.532907

In [67]:
korea_df.loc[(korea_df.인구수<2000000)]

인구수   남자인구수   여자인구수       남여비율
대전광역시  1471640  734441  736599  99.707032
광주광역시  1455048  720060  734988  97.968946

In [68]:
korea_df.loc[(korea_df.인구수 > 2500000)]

인구수    남자인구수    여자인구수        남여비율
서울특별시  9728846  4732275  4988571   94.862336
부산광역시  3404423  1668618  1735805   96.129346
인천광역시  2947217  1476813  1470404  100.435867

In [69]:
korea_df.loc[korea_df.남여비율>100]

인구수    남자인구수    여자인구수        남여비율
인천광역시  2947217  1476813  1470404  100.435867

In [70]:
korea_df.loc[(korea_df.인구수 > 250000) & (korea_df.남여비율 >100)]

인구수    남자인구수    여자인구수        남여비율
인천광역시  2947217  1476813  1470404  100.435867

In [71]:
korea_df.iloc[:3,:2]

인구수    남자인구수
서울특별시  9728846  4732275
부산광역시  3404423  1668618
인천광역시  2947217  1476813

### 다중 인덱싱(Multi Indexing)

* 1차원의 Series와 2차원의 DataFrame 객체를 넘어 3차원, 4차원 이상의 고차원 데이터 처리
* 단일 인덱스 내에 여러 인덱스를 포함하는 다중 인덱싱

#### 다중 인덱스 Series

In [72]:
korea_df

인구수    남자인구수    여자인구수        남여비율
서울특별시  9728846  4732275  4988571   94.862336
부산광역시  3404423  1668618  1735805   96.129346
인천광역시  2947217  1476813  1470404  100.435867
대구광역시  2427954  1198815  1229139   97.532907
대전광역시  1471640   734441   736599   99.707032
광주광역시  1455048   720060   734988   97.968946

In [73]:
idx_tuples = [('서울특별시',2010),('서울특별시',2020),
              ('부산광역시',2010),('부산광역시',2020),
              ('인천광역시',2010),('인천광역시',2020),
              ('대구광역시',2010),('대구광역시',2020),
              ('대전광역시',2010),('대전광역시',2020),
              ('광주광역시',2010),('광주광역시',2020)
              ]
idx_tuples

[('서울특별시', 2010),
 ('서울특별시', 2020),
 ('부산광역시', 2010),
 ('부산광역시', 2020),
 ('인천광역시', 2010),
 ('인천광역시', 2020),
 ('대구광역시', 2010),
 ('대구광역시', 2020),
 ('대전광역시', 2010),
 ('대전광역시', 2020),
 ('광주광역시', 2010),
 ('광주광역시', 2020)]

In [74]:
pop_tuples = [10312545,9720846,2567910,3404423,2758296,2947217,2511676,2427954,1503664,1471040,1454636,1455048]

population = pd.Series(pop_tuples,index=idx_tuples)
population

(서울특별시, 2010)    10312545
(서울특별시, 2020)     9720846
(부산광역시, 2010)     2567910
(부산광역시, 2020)     3404423
(인천광역시, 2010)     2758296
(인천광역시, 2020)     2947217
(대구광역시, 2010)     2511676
(대구광역시, 2020)     2427954
(대전광역시, 2010)     1503664
(대전광역시, 2020)     1471040
(광주광역시, 2010)     1454636
(광주광역시, 2020)     1455048
dtype: int64

In [75]:
midx=pd.MultiIndex.from_tuples(idx_tuples)
midx

MultiIndex([('서울특별시', 2010),
            ('서울특별시', 2020),
            ('부산광역시', 2010),
            ('부산광역시', 2020),
            ('인천광역시', 2010),
            ('인천광역시', 2020),
            ('대구광역시', 2010),
            ('대구광역시', 2020),
            ('대전광역시', 2010),
            ('대전광역시', 2020),
            ('광주광역시', 2010),
            ('광주광역시', 2020)],
           )

In [76]:
population = population.reindex(midx)
population

서울특별시  2010    10312545
       2020     9720846
부산광역시  2010     2567910
       2020     3404423
인천광역시  2010     2758296
       2020     2947217
대구광역시  2010     2511676
       2020     2427954
대전광역시  2010     1503664
       2020     1471040
광주광역시  2010     1454636
       2020     1455048
dtype: int64

In [77]:
population[:,2010]

서울특별시    10312545
부산광역시     2567910
인천광역시     2758296
대구광역시     2511676
대전광역시     1503664
광주광역시     1454636
dtype: int64

In [78]:
population['대전광역시']

2010    1503664
2020    1471040
dtype: int64

In [79]:
korea_mdf = population.unstack()
korea_mdf

2010     2020
광주광역시   1454636  1455048
대구광역시   2511676  2427954
대전광역시   1503664  1471040
부산광역시   2567910  3404423
서울특별시  10312545  9720846
인천광역시   2758296  2947217

In [80]:
korea_mdf.stack() # 다중인덱스 series로 변환

광주광역시  2010     1454636
       2020     1455048
대구광역시  2010     2511676
       2020     2427954
대전광역시  2010     1503664
       2020     1471040
부산광역시  2010     2567910
       2020     3404423
서울특별시  2010    10312545
       2020     9720846
인천광역시  2010     2758296
       2020     2947217
dtype: int64

In [81]:
male_tuple = [5111259,4732275,1773170,1668618,1390356,1476813,1255245,1198815,753648,734441,721780,720060]
male_tuple

[5111259,
 4732275,
 1773170,
 1668618,
 1390356,
 1476813,
 1255245,
 1198815,
 753648,
 734441,
 721780,
 720060]

In [82]:
korea_mdf = pd.DataFrame({'총인구수':population,'남자인구수':male_tuple})
korea_mdf

총인구수    남자인구수
서울특별시 2010  10312545  5111259
      2020   9720846  4732275
부산광역시 2010   2567910  1773170
      2020   3404423  1668618
인천광역시 2010   2758296  1390356
      2020   2947217  1476813
대구광역시 2010   2511676  1255245
      2020   2427954  1198815
대전광역시 2010   1503664   753648
      2020   1471040   734441
광주광역시 2010   1454636   721780
      2020   1455048   720060

In [83]:
korea_mdf['여자인구수']=korea_mdf['총인구수']-korea_mdf['남자인구수']
korea_mdf

총인구수    남자인구수    여자인구수
서울특별시 2010  10312545  5111259  5201286
      2020   9720846  4732275  4988571
부산광역시 2010   2567910  1773170   794740
      2020   3404423  1668618  1735805
인천광역시 2010   2758296  1390356  1367940
      2020   2947217  1476813  1470404
대구광역시 2010   2511676  1255245  1256431
      2020   2427954  1198815  1229139
대전광역시 2010   1503664   753648   750016
      2020   1471040   734441   736599
광주광역시 2010   1454636   721780   732856
      2020   1455048   720060   734988

In [84]:
ratio = korea_mdf['남자인구수']*100/korea_mdf['여자인구수']
ratio

서울특별시  2010     98.269140
       2020     94.862336
부산광역시  2010    223.113219
       2020     96.129346
인천광역시  2010    101.638668
       2020    100.435867
대구광역시  2010     99.905606
       2020     97.532907
대전광역시  2010    100.484256
       2020     99.707032
광주광역시  2010     98.488653
       2020     97.968946
dtype: float64

In [85]:
ratio.unstack()

2010        2020
광주광역시   98.488653   97.968946
대구광역시   99.905606   97.532907
대전광역시  100.484256   99.707032
부산광역시  223.113219   96.129346
서울특별시   98.269140   94.862336
인천광역시  101.638668  100.435867

In [86]:
korea_mdf['남여비율']=ratio
korea_mdf

총인구수    남자인구수    여자인구수        남여비율
서울특별시 2010  10312545  5111259  5201286   98.269140
      2020   9720846  4732275  4988571   94.862336
부산광역시 2010   2567910  1773170   794740  223.113219
      2020   3404423  1668618  1735805   96.129346
인천광역시 2010   2758296  1390356  1367940  101.638668
      2020   2947217  1476813  1470404  100.435867
대구광역시 2010   2511676  1255245  1256431   99.905606
      2020   2427954  1198815  1229139   97.532907
대전광역시 2010   1503664   753648   750016  100.484256
      2020   1471040   734441   736599   99.707032
광주광역시 2010   1454636   721780   732856   98.488653
      2020   1455048   720060   734988   97.968946

#### 다중 인덱스 생성

In [87]:
df=pd.DataFrame(np.random.rand(6,3),index=[['a','a','b','b','c','c'],[1,2,1,2,1,2]],columns=['c1','c2','c3'])
df

c1        c2        c3
a 1  0.469159  0.823877  0.729718
  2  0.866238  0.884895  0.239202
b 1  0.350471  0.655273  0.686968
  2  0.967914  0.210097  0.829638
c 1  0.551570  0.762095  0.467976
  2  0.770132  0.682044  0.126880

In [88]:
pd.MultiIndex.from_arrays([['a','a','b','b','c','c'],[1,2,1,2,1,2]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           )

In [89]:
pd.MultiIndex.from_tuples([('a',1),('a',2),('b',2),('c',1),('c',2)])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           )

In [90]:
pd.MultiIndex.from_product([['a','b','c'],[1,2]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           )

In [91]:
pd.MultiIndex(levels=[['a','b','c'],[1,2]],codes=[[0,0,1,1,2,2],[0,1,0,1,0,1]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           )

In [92]:
population

서울특별시  2010    10312545
       2020     9720846
부산광역시  2010     2567910
       2020     3404423
인천광역시  2010     2758296
       2020     2947217
대구광역시  2010     2511676
       2020     2427954
대전광역시  2010     1503664
       2020     1471040
광주광역시  2010     1454636
       2020     1455048
dtype: int64

In [93]:
population.index.names=['행정구역','년도']
population

행정구역   년도  
서울특별시  2010    10312545
       2020     9720846
부산광역시  2010     2567910
       2020     3404423
인천광역시  2010     2758296
       2020     2947217
대구광역시  2010     2511676
       2020     2427954
대전광역시  2010     1503664
       2020     1471040
광주광역시  2010     1454636
       2020     1455048
dtype: int64

In [94]:
idx=pd.MultiIndex.from_product([['a','b','c'],[1,2]],names=['name1','name2'])
cols=pd.MultiIndex.from_product([['c1','c2','c3'],[1,2]],names=['col_name1','col_name2'])
data = np.round(np.random.randn(6,6),2)
mdf = pd.DataFrame(data,index=idx,columns=cols)
mdf

col_name1      c1          c2          c3      
col_name2       1     2     1     2     1     2
name1 name2                                    
a     1      0.71  0.97  2.50  0.11  0.36  1.10
      2      0.36  0.20 -0.69  0.46 -0.35  0.00
b     1     -1.69  1.01 -0.72  0.54  0.38 -0.70
      2     -0.39 -1.17 -0.84 -0.16 -0.06 -0.28
c     1      0.72  0.82  0.51  2.77 -0.05  0.38
      2     -1.29 -0.78  1.13 -0.15  0.66  0.52

In [95]:
mdf['c2']

col_name2       1     2
name1 name2            
a     1      2.50  0.11
      2     -0.69  0.46
b     1     -0.72  0.54
      2     -0.84 -0.16
c     1      0.51  2.77
      2      1.13 -0.15

#### 인덱싱 및 슬라이싱

In [96]:
population

행정구역   년도  
서울특별시  2010    10312545
       2020     9720846
부산광역시  2010     2567910
       2020     3404423
인천광역시  2010     2758296
       2020     2947217
대구광역시  2010     2511676
       2020     2427954
대전광역시  2010     1503664
       2020     1471040
광주광역시  2010     1454636
       2020     1455048
dtype: int64

In [97]:
population['인천광역시',2010]

2758296

In [98]:
population[:,2010]

행정구역
서울특별시    10312545
부산광역시     2567910
인천광역시     2758296
대구광역시     2511676
대전광역시     1503664
광주광역시     1454636
dtype: int64

In [99]:
population[population > 3000000]

행정구역   년도  
서울특별시  2010    10312545
       2020     9720846
부산광역시  2020     3404423
dtype: int64

In [100]:
population[['대구광역시','대전광역시']]

행정구역   년도  
대구광역시  2010    2511676
       2020    2427954
대전광역시  2010    1503664
       2020    1471040
dtype: int64

In [101]:
mdf['c2',1]

name1  name2
a      1        2.50
       2       -0.69
b      1       -0.72
       2       -0.84
c      1        0.51
       2        1.13
Name: (c2, 1), dtype: float64

In [102]:
mdf.iloc[:3,:4]

col_name1      c1          c2      
col_name2       1     2     1     2
name1 name2                        
a     1      0.71  0.97  2.50  0.11
      2      0.36  0.20 -0.69  0.46
b     1     -1.69  1.01 -0.72  0.54

In [103]:
mdf.loc[:,('c2',1)]

name1  name2
a      1        2.50
       2       -0.69
b      1       -0.72
       2       -0.84
c      1        0.51
       2        1.13
Name: (c2, 1), dtype: float64

In [104]:
idx_slice=pd.IndexSlice
mdf.loc[idx_slice[:,2],idx_slice[:,2]]

col_name1      c1    c2    c3
col_name2       2     2     2
name1 name2                  
a     2      0.20  0.46  0.00
b     2     -1.17 -0.16 -0.28
c     2     -0.78 -0.15  0.52

#### 다중 인덱스 재정렬

In [105]:
idx

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           names=['name1', 'name2'])

In [106]:
korea_mdf

총인구수    남자인구수    여자인구수        남여비율
행정구역  년도                                          
서울특별시 2010  10312545  5111259  5201286   98.269140
      2020   9720846  4732275  4988571   94.862336
부산광역시 2010   2567910  1773170   794740  223.113219
      2020   3404423  1668618  1735805   96.129346
인천광역시 2010   2758296  1390356  1367940  101.638668
      2020   2947217  1476813  1470404  100.435867
대구광역시 2010   2511676  1255245  1256431   99.905606
      2020   2427954  1198815  1229139   97.532907
대전광역시 2010   1503664   753648   750016  100.484256
      2020   1471040   734441   736599   99.707032
광주광역시 2010   1454636   721780   732856   98.488653
      2020   1455048   720060   734988   97.968946

In [107]:
#korea_mdf['서울특별시':'인천광역시'] 정렬 안되어있어서 오류남
korea_mdf = korea_mdf.sort_index()
korea_mdf

총인구수    남자인구수    여자인구수        남여비율
행정구역  년도                                          
광주광역시 2010   1454636   721780   732856   98.488653
      2020   1455048   720060   734988   97.968946
대구광역시 2010   2511676  1255245  1256431   99.905606
      2020   2427954  1198815  1229139   97.532907
대전광역시 2010   1503664   753648   750016  100.484256
      2020   1471040   734441   736599   99.707032
부산광역시 2010   2567910  1773170   794740  223.113219
      2020   3404423  1668618  1735805   96.129346
서울특별시 2010  10312545  5111259  5201286   98.269140
      2020   9720846  4732275  4988571   94.862336
인천광역시 2010   2758296  1390356  1367940  101.638668
      2020   2947217  1476813  1470404  100.435867

In [108]:
korea_mdf['서울특별시':'인천광역시']

총인구수    남자인구수    여자인구수        남여비율
행정구역  년도                                          
서울특별시 2010  10312545  5111259  5201286   98.269140
      2020   9720846  4732275  4988571   94.862336
인천광역시 2010   2758296  1390356  1367940  101.638668
      2020   2947217  1476813  1470404  100.435867

In [109]:
korea_mdf.unstack(level=0)

총인구수                                                 남자인구수           \
행정구역    광주광역시    대구광역시    대전광역시    부산광역시     서울특별시    인천광역시   광주광역시    대구광역시   
년도                                                                             
2010  1454636  2511676  1503664  2567910  10312545  2758296  721780  1255245   
2020  1455048  2427954  1471040  3404423   9720846  2947217  720060  1198815   

                       ...   여자인구수                                  남여비율  \
행정구역   대전광역시    부산광역시  ...   대전광역시    부산광역시    서울특별시    인천광역시      광주광역시   
년도                     ...                                                 
2010  753648  1773170  ...  750016   794740  5201286  1367940  98.488653   
2020  734441  1668618  ...  736599  1735805  4988571  1470404  97.968946   

                                                                
행정구역      대구광역시       대전광역시       부산광역시      서울특별시       인천광역시  
년도                                                              
2010  99.905606  100.484256  223.113219  98.269140  101.638668  
2020  97.532907   99.707032   96.129346  94.862336  100.435867  

[2 rows x 24 columns]

In [110]:
korea_mdf.unstack(level=1)

총인구수             남자인구수             여자인구수                 남여비율  \
년도         2010     2020     2010     2020     2010     2020        2010   
행정구역                                                                       
광주광역시   1454636  1455048   721780   720060   732856   734988   98.488653   
대구광역시   2511676  2427954  1255245  1198815  1256431  1229139   99.905606   
대전광역시   1503664  1471040   753648   734441   750016   736599  100.484256   
부산광역시   2567910  3404423  1773170  1668618   794740  1735805  223.113219   
서울특별시  10312545  9720846  5111259  4732275  5201286  4988571   98.269140   
인천광역시   2758296  2947217  1390356  1476813  1367940  1470404  101.638668   

                   
년도           2020  
행정구역               
광주광역시   97.968946  
대구광역시   97.532907  
대전광역시   99.707032  
부산광역시   96.129346  
서울특별시   94.862336  
인천광역시  100.435867

In [111]:
korea_mdf.stack()

행정구역   년도         
광주광역시  2010  총인구수     1.454636e+06
             남자인구수    7.217800e+05
             여자인구수    7.328560e+05
             남여비율     9.848865e+01
       2020  총인구수     1.455048e+06
             남자인구수    7.200600e+05
             여자인구수    7.349880e+05
             남여비율     9.796895e+01
대구광역시  2010  총인구수     2.511676e+06
             남자인구수    1.255245e+06
             여자인구수    1.256431e+06
             남여비율     9.990561e+01
       2020  총인구수     2.427954e+06
             남자인구수    1.198815e+06
             여자인구수    1.229139e+06
             남여비율     9.753291e+01
대전광역시  2010  총인구수     1.503664e+06
             남자인구수    7.536480e+05
             여자인구수    7.500160e+05
             남여비율     1.004843e+02
       2020  총인구수     1.471040e+06
             남자인구수    7.344410e+05
             여자인구수    7.365990e+05
             남여비율     9.970703e+01
부산광역시  2010  총인구수     2.567910e+06
             남자인구수    1.773170e+06
             여자인구수    7.947400e+05
             남여비율     2.231132e+02
 

In [112]:
korea_mdf

총인구수    남자인구수    여자인구수        남여비율
행정구역  년도                                          
광주광역시 2010   1454636   721780   732856   98.488653
      2020   1455048   720060   734988   97.968946
대구광역시 2010   2511676  1255245  1256431   99.905606
      2020   2427954  1198815  1229139   97.532907
대전광역시 2010   1503664   753648   750016  100.484256
      2020   1471040   734441   736599   99.707032
부산광역시 2010   2567910  1773170   794740  223.113219
      2020   3404423  1668618  1735805   96.129346
서울특별시 2010  10312545  5111259  5201286   98.269140
      2020   9720846  4732275  4988571   94.862336
인천광역시 2010   2758296  1390356  1367940  101.638668
      2020   2947217  1476813  1470404  100.435867

In [113]:
idx_flat = korea_mdf.reset_index(level=0)
idx_flat

행정구역      총인구수    남자인구수    여자인구수        남여비율
년도                                                 
2010  광주광역시   1454636   721780   732856   98.488653
2020  광주광역시   1455048   720060   734988   97.968946
2010  대구광역시   2511676  1255245  1256431   99.905606
2020  대구광역시   2427954  1198815  1229139   97.532907
2010  대전광역시   1503664   753648   750016  100.484256
2020  대전광역시   1471040   734441   736599   99.707032
2010  부산광역시   2567910  1773170   794740  223.113219
2020  부산광역시   3404423  1668618  1735805   96.129346
2010  서울특별시  10312545  5111259  5201286   98.269140
2020  서울특별시   9720846  4732275  4988571   94.862336
2010  인천광역시   2758296  1390356  1367940  101.638668
2020  인천광역시   2947217  1476813  1470404  100.435867

In [114]:
idx_flat = korea_mdf.reset_index(level=(0,1))
idx_flat

행정구역    년도      총인구수    남자인구수    여자인구수        남여비율
0   광주광역시  2010   1454636   721780   732856   98.488653
1   광주광역시  2020   1455048   720060   734988   97.968946
2   대구광역시  2010   2511676  1255245  1256431   99.905606
3   대구광역시  2020   2427954  1198815  1229139   97.532907
4   대전광역시  2010   1503664   753648   750016  100.484256
5   대전광역시  2020   1471040   734441   736599   99.707032
6   부산광역시  2010   2567910  1773170   794740  223.113219
7   부산광역시  2020   3404423  1668618  1735805   96.129346
8   서울특별시  2010  10312545  5111259  5201286   98.269140
9   서울특별시  2020   9720846  4732275  4988571   94.862336
10  인천광역시  2010   2758296  1390356  1367940  101.638668
11  인천광역시  2020   2947217  1476813  1470404  100.435867

In [115]:
#인덱스 다시 살리기
idx_flat.set_index(['행정구역','년도'])

총인구수    남자인구수    여자인구수        남여비율
행정구역  년도                                          
광주광역시 2010   1454636   721780   732856   98.488653
      2020   1455048   720060   734988   97.968946
대구광역시 2010   2511676  1255245  1256431   99.905606
      2020   2427954  1198815  1229139   97.532907
대전광역시 2010   1503664   753648   750016  100.484256
      2020   1471040   734441   736599   99.707032
부산광역시 2010   2567910  1773170   794740  223.113219
      2020   3404423  1668618  1735805   96.129346
서울특별시 2010  10312545  5111259  5201286   98.269140
      2020   9720846  4732275  4988571   94.862336
인천광역시 2010   2758296  1390356  1367940  101.638668
      2020   2947217  1476813  1470404  100.435867

## 데이터 연산

In [116]:
s=pd.Series(np.random.randint(0,10,5))
s

0    8
1    0
2    9
3    5
4    3
dtype: int64

In [117]:
df = pd.DataFrame(np.random.randint(0,10,(3,3)),columns=['A','B','C'])
df

A  B  C
0  2  1  6
1  9  1  4
2  9  8  8

In [118]:
np.exp(s)

0    2980.957987
1       1.000000
2    8103.083928
3     148.413159
4      20.085537
dtype: float64

In [119]:
np.cos(df * np.pi /4)

A         B             C
0  6.123234e-17  0.707107 -1.836970e-16
1  7.071068e-01  0.707107 -1.000000e+00
2  7.071068e-01  1.000000  1.000000e+00

In [120]:
s1 = pd.Series([1,3,5,7,9], index=[0,1,2,3,4])
s2 = pd.Series([2,4,6,8,10],index = [1,2,3,4,5])
s1+s2

0     NaN
1     5.0
2     9.0
3    13.0
4    17.0
5     NaN
dtype: float64

In [121]:
s1.add(s2,fill_value=0)

0     1.0
1     5.0
2     9.0
3    13.0
4    17.0
5    10.0
dtype: float64

In [122]:
df1 = pd.DataFrame(np.random.randint(0,20,(3,3)),columns=list('ACD'))
df1

A  C   D
0   0  8  15
1   8  8   4
2  17  4  15

In [123]:
df2 = pd.DataFrame(np.random.randint(0,20,(5,5)),columns=list('BAECD'))
df2

B   A   E   C   D
0  18  14   5   7  19
1  19  10  14  15  12
2   7   1   3  14  16
3  19  15  12   3  14
4   1   5  19   3  17

In [124]:
df1 + df2

A   B     C     D   E
0  14.0 NaN  15.0  34.0 NaN
1  18.0 NaN  23.0  16.0 NaN
2  18.0 NaN  18.0  31.0 NaN
3   NaN NaN   NaN   NaN NaN
4   NaN NaN   NaN   NaN NaN

In [125]:
fvalue = df1.stack().mean()
df1.add(df2,fill_value=fvalue)

A          B          C          D          E
0  14.000000  26.777778  15.000000  34.000000  13.777778
1  18.000000  27.777778  23.000000  16.000000  22.777778
2  18.000000  15.777778  18.000000  31.000000  11.777778
3  23.777778  27.777778  11.777778  22.777778  20.777778
4  13.777778   9.777778  11.777778  25.777778  27.777778

### 연산자 범용 함수


#### add()

In [126]:
a = np.random.randint(1,10,size=(3,3))
a

array([[4, 1, 7],
       [1, 5, 6],
       [3, 7, 7]])

In [127]:
a+a[0]

array([[ 8,  2, 14],
       [ 5,  6, 13],
       [ 7,  8, 14]])

In [128]:
df = pd.DataFrame(a,columns = list('ABC'))
df

A  B  C
0  4  1  7
1  1  5  6
2  3  7  7

In [129]:
df+df.iloc[0]

A  B   C
0  8  2  14
1  5  6  13
2  7  8  14

In [130]:
df.add(df.iloc[0])

A  B   C
0  8  2  14
1  5  6  13
2  7  8  14

#### sub() / subtract()

In [131]:
a

array([[4, 1, 7],
       [1, 5, 6],
       [3, 7, 7]])

In [132]:
a - a[0]

array([[ 0,  0,  0],
       [-3,  4, -1],
       [-1,  6,  0]])

In [133]:
df

A  B  C
0  4  1  7
1  1  5  6
2  3  7  7

In [134]:
df-df.iloc[0]

A  B  C
0  0  0  0
1 -3  4 -1
2 -1  6  0

In [135]:
df.sub(df.iloc[0])

A  B  C
0  0  0  0
1 -3  4 -1
2 -1  6  0

In [136]:
df.subtract(df['B'],axis=0)

A  B  C
0  3  0  6
1 -4  0  1
2 -4  0  0

#### mul() / multply()




In [137]:
a


array([[4, 1, 7],
       [1, 5, 6],
       [3, 7, 7]])

In [138]:
a * a[1]

array([[ 4,  5, 42],
       [ 1, 25, 36],
       [ 3, 35, 42]])

In [139]:
df


A  B  C
0  4  1  7
1  1  5  6
2  3  7  7

In [140]:
df*df.iloc[1]

A   B   C
0  4   5  42
1  1  25  36
2  3  35  42

In [141]:
df.mul(df.iloc[1])

A   B   C
0  4   5  42
1  1  25  36
2  3  35  42

In [142]:
df.multiply(df.iloc[2])

A   B   C
0  12   7  49
1   3  35  42
2   9  49  49

#### truediv() /  div() / divide() / floordiv()

In [143]:
a

array([[4, 1, 7],
       [1, 5, 6],
       [3, 7, 7]])

In [144]:
a/a[0]

array([[1.        , 1.        , 1.        ],
       [0.25      , 5.        , 0.85714286],
       [0.75      , 7.        , 1.        ]])

In [145]:
df/df.iloc[0]

A    B         C
0  1.00  1.0  1.000000
1  0.25  5.0  0.857143
2  0.75  7.0  1.000000

In [146]:
df.truediv(df.iloc[0])

A    B         C
0  1.00  1.0  1.000000
1  0.25  5.0  0.857143
2  0.75  7.0  1.000000

In [147]:
df.div(df.iloc[1])

A    B         C
0  4.0  0.2  1.166667
1  1.0  1.0  1.000000
2  3.0  1.4  1.166667

In [148]:
df.divide(df.iloc[2])

A         B         C
0  1.333333  0.142857  1.000000
1  0.333333  0.714286  0.857143
2  1.000000  1.000000  1.000000

In [149]:
a//a[2]

array([[1, 0, 1],
       [0, 0, 0],
       [1, 1, 1]])

In [150]:
df.floordiv(df.iloc[2])

A  B  C
0  1  0  1
1  0  0  0
2  1  1  1

#### mod()

In [151]:
a

array([[4, 1, 7],
       [1, 5, 6],
       [3, 7, 7]])

In [152]:
a % a[0]

array([[0, 0, 0],
       [1, 0, 6],
       [3, 0, 0]])

In [153]:
df

A  B  C
0  4  1  7
1  1  5  6
2  3  7  7

In [154]:
df.mod(df.iloc[0])

A  B  C
0  0  0  0
1  1  0  6
2  3  0  0

#### pow()

In [155]:
a ** a[0]

array([[   256,      1, 823543],
       [     1,      5, 279936],
       [    81,      7, 823543]])

In [156]:
df.pow(df.iloc[0])

A  B       C
0  256  1  823543
1    1  5  279936
2   81  7  823543

In [157]:
row = df.iloc[0,::2]
row

A    4
C    7
Name: 0, dtype: int64

In [158]:
df - row

A   B    C
0  0.0 NaN  0.0
1 -3.0 NaN -1.0
2 -1.0 NaN  0.0

### 정렬(Sort)

In [159]:
s = pd.Series(range(5),index=['A','D','B','C','E'])
s

A    0
D    1
B    2
C    3
E    4
dtype: int64

In [160]:
s.sort_index()

A    0
B    2
C    3
D    1
E    4
dtype: int64

In [161]:
s.sort_values()

A    0
D    1
B    2
C    3
E    4
dtype: int64

In [162]:
df= pd.DataFrame(np.random.randint(0,10,(4,4)),index=[2,4,1,3],columns=list('BDAC'))
df

B  D  A  C
2  1  0  9  9
4  5  4  3  1
1  2  9  4  3
3  1  8  8  2

In [163]:
df.sort_index()

B  D  A  C
1  2  9  4  3
2  1  0  9  9
3  1  8  8  2
4  5  4  3  1

In [164]:
df.sort_values(by='A')

B  D  A  C
4  5  4  3  1
1  2  9  4  3
3  1  8  8  2
2  1  0  9  9

In [165]:
df.sort_values(by=['A','C'])

B  D  A  C
4  5  4  3  1
1  2  9  4  3
3  1  8  8  2
2  1  0  9  9

### 순위(Ranking)


In [166]:
s = pd.Series([-2,4,7,3,0,7,5,-4,2,6])
s

0   -2
1    4
2    7
3    3
4    0
5    7
6    5
7   -4
8    2
9    6
dtype: int64

In [167]:
s.rank()

0    2.0
1    6.0
2    9.5
3    5.0
4    3.0
5    9.5
6    7.0
7    1.0
8    4.0
9    8.0
dtype: float64

In [168]:
s.rank(method='first') #같은 값이 있을 때 먼저 나온 값에 순위를 더 높게

0     2.0
1     6.0
2     9.0
3     5.0
4     3.0
5    10.0
6     7.0
7     1.0
8     4.0
9     8.0
dtype: float64

In [169]:
s.rank(method='max')

0     2.0
1     6.0
2    10.0
3     5.0
4     3.0
5    10.0
6     7.0
7     1.0
8     4.0
9     8.0
dtype: float64

### 고성능 연산

In [170]:
nrows, ncols = 100000,100
df1,df2,df3,df4 = (pd.DataFrame(np.random.rand(nrows,ncols)) for i in range(4))

In [171]:
%timeit df1+df2+df3+df4

10 loops, best of 5: 60.8 ms per loop


In [172]:
#%timeit pd.eval('df1+df2+df3+df4')

In [173]:
%timeit df * -df2 /(-df3 * df4)

1 loop, best of 5: 344 ms per loop


In [174]:
#%timeit pd.eval('df1 * -df2 / (-df3 * df4)')

In [175]:
%timeit (df1<df2) & (df2 <=df3) & (df3 != df4)

10 loops, best of 5: 60.5 ms per loop


In [176]:
#%timeit pd.eval('(df1<df2) & (df2 <=df3) & (df3 != df4)')

In [177]:
df = pd.DataFrame(np.random.rand(1000000,5),columns=['A','B','C','D','E'])
df.head()

A         B         C         D         E
0  0.086167  0.720691  0.114183  0.858720  0.411134
1  0.801614  0.686163  0.750713  0.110961  0.424756
2  0.365711  0.329150  0.641939  0.819875  0.291810
3  0.371444  0.090580  0.437713  0.473167  0.518873
4  0.323853  0.509849  0.746044  0.395053  0.744973

In [178]:
%timeit df['A']+df['B']/df['C']-df['D'] * df['E']

100 loops, best of 5: 17.4 ms per loop


In [ ]:
#%timeit pd.eval('df.A+df.B/df.C-df.D * df.E')

## 데이터 결합

### Concat() / Append()

In [179]:
s1 = pd.Series(['a','b'],index=[1,2])
s2 = pd.Series(['c','d'],index=[3,4])
pd.concat([s1,s2])

1    a
2    b
3    c
4    d
dtype: object

In [181]:
def create_df(cols,idx):
  data = {c:[str(c.lower())+str(i) for i in idx] for c in cols}
  return pd.DataFrame(data,idx)

In [182]:
df1 = create_df('AB',[1,2])
df1

A   B
1  a1  b1
2  a2  b2

In [183]:
df2 = create_df('AB',[3,4])
df2

A   B
3  a3  b3
4  a4  b4

In [185]:
pd.concat([df1,df2])

A   B
1  a1  b1
2  a2  b2
3  a3  b3
4  a4  b4

In [188]:
df3 = create_df('AB',[0,1])
df3

A   B
0  a0  b0
1  a1  b1

In [186]:
df4 = create_df('CD',[0,1])
df4

C   D
0  c0  d0
1  c1  d1

In [189]:
pd.concat([df3,df4]) # column이 다르면 누락값으로 나타남

A    B    C    D
0   a0   b0  NaN  NaN
1   a1   b1  NaN  NaN
0  NaN  NaN   c0   d0
1  NaN  NaN   c1   d1

In [196]:
pd.concat([df3,df4],axis=1)

A   B   C   D
0  a0  b0  c0  d0
1  a1  b1  c1  d1

In [197]:
pd.concat([df1,df3])

A   B
1  a1  b1
2  a2  b2
0  a0  b0
1  a1  b1

In [ ]:
#pd.concat([df1,df3],verify_integrity=True) 결합을 하면 안된다는 오류 남.


In [191]:
pd.concat([df1,df3],ignore_index=True)

A   B
0  a1  b1
1  a2  b2
2  a0  b0
3  a1  b1

In [192]:
pd.concat([df1,df3],keys=['X','Y'])

A   B
X 1  a1  b1
  2  a2  b2
Y 0  a0  b0
  1  a1  b1

In [193]:
df5 = create_df('ABC',[1,2])
df6 = create_df('BCD',[3,4])
pd.concat([df5,df6])

A   B   C    D
1   a1  b1  c1  NaN
2   a2  b2  c2  NaN
3  NaN  b3  c3   d3
4  NaN  b4  c4   d4

In [194]:
pd.concat([df5,df6],join='inner')

B   C
1  b1  c1
2  b2  c2
3  b3  c3
4  b4  c4

In [195]:
df5.append(df6)

A   B   C    D
1   a1  b1  c1  NaN
2   a2  b2  c2  NaN
3  NaN  b3  c3   d3
4  NaN  b4  c4   d4

### 병합과 조인

In [198]:
df1 = pd.DataFrame({'학생':['홍길동','이순신','임꺽정','김유신'],'학과':['경영학과','교육학과','컴퓨터학과','통계학과']})
df1

학생     학과
0  홍길동   경영학과
1  이순신   교육학과
2  임꺽정  컴퓨터학과
3  김유신   통계학과

In [199]:
df2 = pd.DataFrame({'학생':['홍길동','이순신','임꺽정','김유신'],'입학년도':[2012,2016,2019,2020]})
df2

학생  입학년도
0  홍길동  2012
1  이순신  2016
2  임꺽정  2019
3  김유신  2020

In [200]:
df3 = pd.merge(df1,df2)
df3

학생     학과  입학년도
0  홍길동   경영학과  2012
1  이순신   교육학과  2016
2  임꺽정  컴퓨터학과  2019
3  김유신   통계학과  2020

In [202]:
df4 = pd.DataFrame({'학과': ['경영학과','교육학과','컴퓨터학과','통계학과'],
                   '학과장':['황희','장영실','안창호','정약용']})
df4

학과  학과장
0   경영학과   황희
1   교육학과  장영실
2  컴퓨터학과  안창호
3   통계학과  정약용

In [203]:
pd.merge(df3,df4)

학생     학과  입학년도  학과장
0  홍길동   경영학과  2012   황희
1  이순신   교육학과  2016  장영실
2  임꺽정  컴퓨터학과  2019  안창호
3  김유신   통계학과  2020  정약용

In [204]:
df5 = pd.DataFrame({'학과':['경영학과','교육학과','교육학과','컴퓨터학과','컴퓨터학과','통계학과'],
                    '과목':['경영개론','기초수학','물리학','프로그래밍','운영체제','확률론']})
df5

학과     과목
0   경영학과   경영개론
1   교육학과   기초수학
2   교육학과    물리학
3  컴퓨터학과  프로그래밍
4  컴퓨터학과   운영체제
5   통계학과    확률론

In [205]:
pd.merge(df1,df5)

학생     학과     과목
0  홍길동   경영학과   경영개론
1  이순신   교육학과   기초수학
2  이순신   교육학과    물리학
3  임꺽정  컴퓨터학과  프로그래밍
4  임꺽정  컴퓨터학과   운영체제
5  김유신   통계학과    확률론

In [206]:
pd.merge(df1,df2,on='학생')

학생     학과  입학년도
0  홍길동   경영학과  2012
1  이순신   교육학과  2016
2  임꺽정  컴퓨터학과  2019
3  김유신   통계학과  2020

In [207]:
df6 = pd.DataFrame({'이름': ['홍길동','이순신','임꺽정','김유신'],
                    '성적': ['A','A+','B','A+']})
df6

이름  성적
0  홍길동   A
1  이순신  A+
2  임꺽정   B
3  김유신  A+

In [208]:
pd.merge(df1,df6,left_on="학생",right_on="이름")

학생     학과   이름  성적
0  홍길동   경영학과  홍길동   A
1  이순신   교육학과  이순신  A+
2  임꺽정  컴퓨터학과  임꺽정   B
3  김유신   통계학과  김유신  A+

In [209]:
pd.merge(df1,df6,left_on='학생',right_on='이름').drop('이름',axis=1)

학생     학과  성적
0  홍길동   경영학과   A
1  이순신   교육학과  A+
2  임꺽정  컴퓨터학과   B
3  김유신   통계학과  A+

In [210]:
mdf1 = df1.set_index('학생')
mdf2 = df2.set_index('학생')

In [211]:
mdf1

학과
학생        
홍길동   경영학과
이순신   교육학과
임꺽정  컴퓨터학과
김유신   통계학과

In [212]:
mdf2

입학년도
학생       
홍길동  2012
이순신  2016
임꺽정  2019
김유신  2020

In [213]:
pd.merge(mdf1,mdf2,left_index=True,right_index=True)

학과  입학년도
학생              
홍길동   경영학과  2012
이순신   교육학과  2016
임꺽정  컴퓨터학과  2019
김유신   통계학과  2020

In [214]:
mdf1.join(mdf2)

학과  입학년도
학생              
홍길동   경영학과  2012
이순신   교육학과  2016
임꺽정  컴퓨터학과  2019
김유신   통계학과  2020

In [215]:
pd.merge(mdf1,df6,left_index=True,right_on='이름')

학과   이름  성적
0   경영학과  홍길동   A
1   교육학과  이순신  A+
2  컴퓨터학과  임꺽정   B
3   통계학과  김유신  A+

In [216]:
df7 = pd.DataFrame({'이름':['홍길동','이순신','임꺽정'],'주문음식':['햄버거','피자','짜장면']})
df7

이름 주문음식
0  홍길동  햄버거
1  이순신   피자
2  임꺽정  짜장면

In [217]:
df8 = pd.DataFrame({'이름':['홍길동','이순신','김유신'],'주문음료':['콜라','사이다','커피']})
df8

이름 주문음료
0  홍길동   콜라
1  이순신  사이다
2  김유신   커피

In [218]:
pd.merge(df7,df8) # 둘다 데이터가 있는 행만 남음

이름 주문음식 주문음료
0  홍길동  햄버거   콜라
1  이순신   피자  사이다

In [219]:
pd.merge(df7,df8,how='inner') #default 값

이름 주문음식 주문음료
0  홍길동  햄버거   콜라
1  이순신   피자  사이다

In [220]:
pd.merge(df7,df8,how='outer')

이름 주문음식 주문음료
0  홍길동  햄버거   콜라
1  이순신   피자  사이다
2  임꺽정  짜장면  NaN
3  김유신  NaN   커피

In [221]:
pd.merge(df7,df8,how='left') #df7 기준

이름 주문음식 주문음료
0  홍길동  햄버거   콜라
1  이순신   피자  사이다
2  임꺽정  짜장면  NaN

In [222]:
pd.merge(df7,df8,how='right')

이름 주문음식 주문음료
0  홍길동  햄버거   콜라
1  이순신   피자  사이다
2  김유신  NaN   커피

In [226]:
df9 = pd.DataFrame({'이름':['홍길동','이순신','임꺽정','김유신'],'순위':[3,2,4,1]})
df9

이름  순위
0  홍길동   3
1  이순신   2
2  임꺽정   4
3  김유신   1

In [227]:
df10 = pd.DataFrame({'이름':['홍길동','이순신','임꺽정','김유신'],'순위':[4,1,3,2]})

In [228]:
pd.merge(df9,df10,on='이름')

이름  순위_x  순위_y
0  홍길동     3     4
1  이순신     2     1
2  임꺽정     4     3
3  김유신     1     2

In [229]:
pd.merge(df9,df10,on='이름',suffixes=['_인기','_성적'])

이름  순위_인기  순위_성적
0  홍길동      3      4
1  이순신      2      1
2  임꺽정      4      3
3  김유신      1      2

## 데이터 집계와 그룹 연산

#### 집계 연산(Aggregation)


### GroupBy 연산

### 피벗 테이블(Pivot Table)


### 범주형(Categorical) 데이터


## 문자열 연산

#### 문자열 연산자

#### 기타 연산자


#### 정규표현식


## 시계열 처리

#### 시계열 데이터 구조


### 시계열 기본

### 주기와 오프셋


### 시프트(Shift)

### 시간대 처리

* 국제표준시(Coordinated Universal Time, UTC)를 기준으로 떨어진 거리만큼 오프셋으로 시간대 처리
* 전 세계의 시간대 정보를 모아놓은 올슨 데이터베이스를 활용한 라이브러리인 `pytz` 사용

### 기간과 기간 연산

### 리샘플링(Resampling)

* 리샘플링(Resampling): 시계열의 빈도 변환
* 다운샘플링(Down sampling): 상위 빈도 데이터를 하위 빈도 데이터로 집계
* 업샘플링(Up sampling): 하위 빈도 데이터를 상위 빈도 데이터로 집계

### 무빙 윈도우(Moving Window)

## 데이터 읽기 및 저장


### 텍스트 파일 읽기/쓰기

### 이진 데이터 파일 읽기/쓰기

## 데이터 정제

### 누락값 처리

* 대부분의 실제 데이터들은 정제되지 않고 누락값들이 존재
* 서로 다른 데이터들은 다른 형태의 결측을 가짐
* 결측 데이터는 `null`, `NaN`, `NA`로 표기

#### None: 파이썬 누락 데이터

#### NaN: 누락된 수치 데이터

#### Null 값 처리


### 중복 제거

### 값 치환

## 참고문헌

* Pandas 사이트: https://pandas.pydata.org/
* Jake VanderPlas, "Python Data Science Handbook", O'Reilly
* Wes Mckinney, "Python for Data Analysis", O'Reilly