<a href="https://colab.research.google.com/github/hyeonniii/NLP/blob/main/_Pandas_%ED%95%9C%EB%B2%88%EC%97%90_%EC%A0%9C%EB%8C%80%EB%A1%9C_%EB%B0%B0%EC%9A%B0%EA%B8%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas 한번에 제대로 배우기




---



In [4]:
import numpy as np
import pandas as pd
pd.__version__

'1.3.5'

## Pandas 객체


### Series 객체

In [5]:
s = pd.Series([0,0.25,0.5,0.75,1.0])
s

0    0.00
1    0.25
2    0.50
3    0.75
4    1.00
dtype: float64

In [6]:
s.values

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [7]:
s.index

RangeIndex(start=0, stop=5, step=1)

In [8]:
s[1]

0.25

In [9]:
s[1:4]

1    0.25
2    0.50
3    0.75
dtype: float64

In [10]:
s = pd.Series([0,0.25,0.5,0.75,1.0], index = ['a','b','c','d','e'])
s


a    0.00
b    0.25
c    0.50
d    0.75
e    1.00
dtype: float64

In [11]:
s['c']

0.5

In [12]:
s[['c','d','e']]

c    0.50
d    0.75
e    1.00
dtype: float64

In [13]:
'b' in s

True

In [14]:
s = pd.Series([0,0.25,0.5,0.75,1.0],index=[2,4,6,8,10])
s

2     0.00
4     0.25
6     0.50
8     0.75
10    1.00
dtype: float64

In [15]:
s[4]

0.25

In [16]:
s[2:]

6     0.50
8     0.75
10    1.00
dtype: float64

In [17]:
s.unique()

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [18]:
s.value_counts()

0.00    1
0.25    1
0.50    1
0.75    1
1.00    1
dtype: int64

In [19]:
s.isin([0.25, 0.75])

2     False
4      True
6     False
8      True
10    False
dtype: bool

In [20]:
pop_tuple = {'서울특별시':9728846,'부산광역시':3404423,'인천광역시':2947217,'대구광역시':2427954,'대전광역시':1471640,'광주광역시':1455048}
population = pd.Series(pop_tuple)
population

서울특별시    9728846
부산광역시    3404423
인천광역시    2947217
대구광역시    2427954
대전광역시    1471640
광주광역시    1455048
dtype: int64

In [21]:
population['서울특별시']

9728846

In [22]:
population['서울특별시':'인천광역시']

서울특별시    9728846
부산광역시    3404423
인천광역시    2947217
dtype: int64

### DataFrame 객체

In [23]:
pd.DataFrame([{'A':2,'B':4,'D':3},{'A':4,'B':5,'C':7}])

A  B    D    C
0  2  4  3.0  NaN
1  4  5  NaN  7.0

In [24]:
pd.DataFrame(np.random.rand(5,5),columns=['A','B','C','D','E'], index=[1,2,3,4,5])

A         B         C         D         E
1  0.627873  0.954251  0.902467  0.189303  0.168018
2  0.365367  0.310311  0.430264  0.094988  0.144632
3  0.684148  0.153142  0.210297  0.779954  0.841486
4  0.465470  0.386633  0.845259  0.318763  0.650865
5  0.457034  0.803998  0.817616  0.850967  0.008248

In [69]:
male_tuple = {'서울특별시':4732275,'부산광역시':1668618,'인천광역시':1476813,'대구광역시':1198815,'대전광역시':734441,'광주광역시':720060}
male = pd.Series(male_tuple)
male

서울특별시    4732275
부산광역시    1668618
인천광역시    1476813
대구광역시    1198815
대전광역시     734441
광주광역시     720060
dtype: int64

In [26]:
female_tuple = {'서울특별시':4988571,'부산광역시':1735805,'인천광역시':1470404,'대구광역시':1229139,'대전광역시':736599,'광주광역시':734988}
female = pd.Series(female_tuple)
female

서울특별시    4988571
부산광역시    1735805
인천광역시    1470404
대구광역시    1229139
대전광역시     736599
광주광역시     734988
dtype: int64

In [70]:
korea_df = pd.DataFrame({'인구수':population,'남자인구수':male,'여자인구수':female})
korea_df

인구수    남자인구수    여자인구수
서울특별시  9728846  4732275  4988571
부산광역시  3404423  1668618  1735805
인천광역시  2947217  1476813  1470404
대구광역시  2427954  1198815  1229139
대전광역시  1471640   734441   736599
광주광역시  1455048   720060   734988

In [28]:
korea_df.index

Index(['서울특별시', '부산광역시', '인천광역시', '대구광역시', '대전광역시', '광주광역시'], dtype='object')

In [29]:
korea_df.columns

Index(['인구수', '남자인구수', '여자인구수'], dtype='object')

In [30]:
korea_df['여자인구수']

서울특별시    4988571
부산광역시    1735805
인천광역시    1470404
대구광역시    1229139
대전광역시     736599
광주광역시     734988
Name: 여자인구수, dtype: int64

In [31]:
korea_df['서울특별시':'인천광역시']

인구수    남자인구수    여자인구수
서울특별시  9728846   473275  4988571
부산광역시  3404423  1668618  1735805
인천광역시  2947217  1476813  1470404

### Index 객체


In [32]:
idx = pd.Index([2,4,6,8,10])
idx

Int64Index([2, 4, 6, 8, 10], dtype='int64')

In [33]:
idx[1]

4

In [34]:
idx[1:2:2]

Int64Index([4], dtype='int64')

In [35]:
idx[-1::]

Int64Index([10], dtype='int64')

In [36]:
idx[::2]

Int64Index([2, 6, 10], dtype='int64')

In [37]:
print(idx)
print(idx.size)
print(idx.shape)
print(idx.ndim)
print(idx.dtype)

Int64Index([2, 4, 6, 8, 10], dtype='int64')
5
(5,)
1
int64


#### Index 연산

In [38]:
idx1 = pd.Index([1,2,4,6,8])
idx2 = pd.Index([2,4,5,6,7])
print(idx1.append(idx2))
print(idx1.difference(idx2)) # 차집합
print(idx1 - idx2)
print(idx1.intersection(idx2))
print(idx1 & idx2)
print(idx1.union(idx2))
print(idx1 | idx2)
print(idx1.delete(0))
print(idx1.drop(1))
print(idx1 ^ idx2) # 여집합

Int64Index([1, 2, 4, 6, 8, 2, 4, 5, 6, 7], dtype='int64')
Int64Index([1, 8], dtype='int64')
Int64Index([-1, -2, -1, 0, 1], dtype='int64')
Int64Index([2, 4, 6], dtype='int64')
Int64Index([2, 4, 6], dtype='int64')
Int64Index([1, 2, 4, 5, 6, 7, 8], dtype='int64')
Int64Index([1, 2, 4, 5, 6, 7, 8], dtype='int64')
Int64Index([2, 4, 6, 8], dtype='int64')
Int64Index([2, 4, 6, 8], dtype='int64')
Int64Index([1, 5, 7, 8], dtype='int64')


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: FutureWarning: Index.__and__ operating as a set operation is deprecated, in the future this will be a logical operation matching Series.__and__.  Use index.intersection(other) instead
  import sys
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: FutureWarning: Index.__or__ operating as a set operation is deprecated, in the future this will be a logical operation matching Series.__or__.  Use index.union(other) instead
  if __name__ == '__main__':
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:12: FutureWarning: Index.__xor__ operating as a set operation is deprecated, in the future this will be a logical operation matching Series.__xor__.  Use index.symmetric_difference(other) instead
  if sys.path[0] == '':




---



## 인덱싱(Indexing)

In [39]:
s = pd.Series([0,0.25,0.5,0.75,1.0],index = ['a','b','c','d','e'])
s

a    0.00
b    0.25
c    0.50
d    0.75
e    1.00
dtype: float64

In [40]:
'b' in s

True

In [41]:
s['b']

0.25

In [42]:
s.keys()

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [43]:
list(s.items())

[('a', 0.0), ('b', 0.25), ('c', 0.5), ('d', 0.75), ('e', 1.0)]

In [44]:
s['f']=1.25
s

a    0.00
b    0.25
c    0.50
d    0.75
e    1.00
f    1.25
dtype: float64

In [45]:
s['a':'d']

a    0.00
b    0.25
c    0.50
d    0.75
dtype: float64

In [46]:
s[0:4]

a    0.00
b    0.25
c    0.50
d    0.75
dtype: float64

In [47]:
s[(s>0.4)&(s<0.8)]

c    0.50
d    0.75
dtype: float64

In [48]:
s[['a','c','e']]

a    0.0
c    0.5
e    1.0
dtype: float64

### Series 인덱싱

In [49]:
s=pd.Series(['a','b','c','d','e'],index=[1,3,5,7,9])
s

1    a
3    b
5    c
7    d
9    e
dtype: object

In [50]:
s[1]

'a'

In [51]:
s[2:4]

5    c
7    d
dtype: object

In [52]:
s.iloc[1]

'b'

In [53]:
s.iloc[2:4]

5    c
7    d
dtype: object

In [54]:
s.reindex(range(10))

0    NaN
1      a
2    NaN
3      b
4    NaN
5      c
6    NaN
7      d
8    NaN
9      e
dtype: object

In [55]:
s.reindex(range(10),method='bfill')

0    a
1    a
2    b
3    b
4    c
5    c
6    d
7    d
8    e
9    e
dtype: object

### DataFrame 인덱싱


In [71]:
korea_df

인구수    남자인구수    여자인구수
서울특별시  9728846  4732275  4988571
부산광역시  3404423  1668618  1735805
인천광역시  2947217  1476813  1470404
대구광역시  2427954  1198815  1229139
대전광역시  1471640   734441   736599
광주광역시  1455048   720060   734988

In [57]:
korea_df['남자인구수']

서울특별시     473275
부산광역시    1668618
인천광역시    1476813
대구광역시    1198815
대전광역시     734441
광주광역시     720060
Name: 남자인구수, dtype: int64

In [58]:
korea_df.남자인구수

서울특별시     473275
부산광역시    1668618
인천광역시    1476813
대구광역시    1198815
대전광역시     734441
광주광역시     720060
Name: 남자인구수, dtype: int64

In [59]:
korea_df.여자인구수

서울특별시    4988571
부산광역시    1735805
인천광역시    1470404
대구광역시    1229139
대전광역시     736599
광주광역시     734988
Name: 여자인구수, dtype: int64

In [72]:
korea_df['남여비율'] = (korea_df['남자인구수']*100/korea_df['여자인구수'])

In [74]:
korea_df.남여비율

서울특별시     94.862336
부산광역시     96.129346
인천광역시    100.435867
대구광역시     97.532907
대전광역시     99.707032
광주광역시     97.968946
Name: 남여비율, dtype: float64

In [62]:
korea_df.values

array([[9.72884600e+06, 4.73275000e+05, 4.98857100e+06, 9.48718581e+00],
       [3.40442300e+06, 1.66861800e+06, 1.73580500e+06, 9.61293463e+01],
       [2.94721700e+06, 1.47681300e+06, 1.47040400e+06, 1.00435867e+02],
       [2.42795400e+06, 1.19881500e+06, 1.22913900e+06, 9.75329072e+01],
       [1.47164000e+06, 7.34441000e+05, 7.36599000e+05, 9.97070319e+01],
       [1.45504800e+06, 7.20060000e+05, 7.34988000e+05, 9.79689464e+01]])

In [73]:
korea_df.T

서울특별시         부산광역시         인천광역시         대구광역시         대전광역시  \
인구수    9.728846e+06  3.404423e+06  2.947217e+06  2.427954e+06  1.471640e+06   
남자인구수  4.732275e+06  1.668618e+06  1.476813e+06  1.198815e+06  7.344410e+05   
여자인구수  4.988571e+06  1.735805e+06  1.470404e+06  1.229139e+06  7.365990e+05   
남여비율   9.486234e+01  9.612935e+01  1.004359e+02  9.753291e+01  9.970703e+01   

              광주광역시  
인구수    1.455048e+06  
남자인구수  7.200600e+05  
여자인구수  7.349880e+05  
남여비율   9.796895e+01

In [64]:
korea_df.values[0]

array([9.72884600e+06, 4.73275000e+05, 4.98857100e+06, 9.48718581e+00])

In [65]:
korea_df['인구수']

서울특별시    9728846
부산광역시    3404423
인천광역시    2947217
대구광역시    2427954
대전광역시    1471640
광주광역시    1455048
Name: 인구수, dtype: int64

In [66]:
korea_df.loc[:'인천광역시',:'남자인구수']

인구수    남자인구수
서울특별시  9728846   473275
부산광역시  3404423  1668618
인천광역시  2947217  1476813

In [75]:
korea_df.loc[(korea_df.여자인구수 > 1000000)]

인구수    남자인구수    여자인구수        남여비율
서울특별시  9728846  4732275  4988571   94.862336
부산광역시  3404423  1668618  1735805   96.129346
인천광역시  2947217  1476813  1470404  100.435867
대구광역시  2427954  1198815  1229139   97.532907

In [76]:
korea_df.loc[(korea_df.인구수<2000000)]

인구수   남자인구수   여자인구수       남여비율
대전광역시  1471640  734441  736599  99.707032
광주광역시  1455048  720060  734988  97.968946

In [77]:
korea_df.loc[(korea_df.인구수 > 2500000)]

인구수    남자인구수    여자인구수        남여비율
서울특별시  9728846  4732275  4988571   94.862336
부산광역시  3404423  1668618  1735805   96.129346
인천광역시  2947217  1476813  1470404  100.435867

In [78]:
korea_df.loc[korea_df.남여비율>100]

인구수    남자인구수    여자인구수        남여비율
인천광역시  2947217  1476813  1470404  100.435867

In [79]:
korea_df.loc[(korea_df.인구수 > 250000) & (korea_df.남여비율 >100)]

인구수    남자인구수    여자인구수        남여비율
인천광역시  2947217  1476813  1470404  100.435867

In [80]:
korea_df.iloc[:3,:2]

인구수    남자인구수
서울특별시  9728846  4732275
부산광역시  3404423  1668618
인천광역시  2947217  1476813

### 다중 인덱싱(Multi Indexing)

* 1차원의 Series와 2차원의 DataFrame 객체를 넘어 3차원, 4차원 이상의 고차원 데이터 처리
* 단일 인덱스 내에 여러 인덱스를 포함하는 다중 인덱싱

#### 다중 인덱스 Series

In [81]:
korea_df

인구수    남자인구수    여자인구수        남여비율
서울특별시  9728846  4732275  4988571   94.862336
부산광역시  3404423  1668618  1735805   96.129346
인천광역시  2947217  1476813  1470404  100.435867
대구광역시  2427954  1198815  1229139   97.532907
대전광역시  1471640   734441   736599   99.707032
광주광역시  1455048   720060   734988   97.968946

In [82]:
idx_tuples = [('서울특별시',2010),('서울특별시',2020),
              ('부산광역시',2010),('부산광역시',2020),
              ('인천광역시',2010),('인천광역시',2020),
              ('대구광역시',2010),('대구광역시',2020),
              ('대전광역시',2010),('대전광역시',2020),
              ('광주광역시',2010),('광주광역시',2020)
              ]
idx_tuples

[('서울특별시', 2010),
 ('서울특별시', 2020),
 ('부산광역시', 2010),
 ('부산광역시', 2020),
 ('인천광역시', 2010),
 ('인천광역시', 2020),
 ('대구광역시', 2010),
 ('대구광역시', 2020),
 ('대전광역시', 2010),
 ('대전광역시', 2020),
 ('광주광역시', 2010),
 ('광주광역시', 2020)]

In [83]:
pop_tuples = [10312545,9720846,2567910,3404423,2758296,2947217,2511676,2427954,1503664,1471040,1454636,1455048]

population = pd.Series(pop_tuples,index=idx_tuples)
population

(서울특별시, 2010)    10312545
(서울특별시, 2020)     9720846
(부산광역시, 2010)     2567910
(부산광역시, 2020)     3404423
(인천광역시, 2010)     2758296
(인천광역시, 2020)     2947217
(대구광역시, 2010)     2511676
(대구광역시, 2020)     2427954
(대전광역시, 2010)     1503664
(대전광역시, 2020)     1471040
(광주광역시, 2010)     1454636
(광주광역시, 2020)     1455048
dtype: int64

In [84]:
midx=pd.MultiIndex.from_tuples(idx_tuples)
midx

MultiIndex([('서울특별시', 2010),
            ('서울특별시', 2020),
            ('부산광역시', 2010),
            ('부산광역시', 2020),
            ('인천광역시', 2010),
            ('인천광역시', 2020),
            ('대구광역시', 2010),
            ('대구광역시', 2020),
            ('대전광역시', 2010),
            ('대전광역시', 2020),
            ('광주광역시', 2010),
            ('광주광역시', 2020)],
           )

In [85]:
population = population.reindex(midx)
population

서울특별시  2010    10312545
       2020     9720846
부산광역시  2010     2567910
       2020     3404423
인천광역시  2010     2758296
       2020     2947217
대구광역시  2010     2511676
       2020     2427954
대전광역시  2010     1503664
       2020     1471040
광주광역시  2010     1454636
       2020     1455048
dtype: int64

In [86]:
population[:,2010]

서울특별시    10312545
부산광역시     2567910
인천광역시     2758296
대구광역시     2511676
대전광역시     1503664
광주광역시     1454636
dtype: int64

In [87]:
population['대전광역시']

2010    1503664
2020    1471040
dtype: int64

In [88]:
korea_mdf = population.unstack()
korea_mdf

2010     2020
광주광역시   1454636  1455048
대구광역시   2511676  2427954
대전광역시   1503664  1471040
부산광역시   2567910  3404423
서울특별시  10312545  9720846
인천광역시   2758296  2947217

In [89]:
korea_mdf.stack() # 다중인덱스 series로 변환

광주광역시  2010     1454636
       2020     1455048
대구광역시  2010     2511676
       2020     2427954
대전광역시  2010     1503664
       2020     1471040
부산광역시  2010     2567910
       2020     3404423
서울특별시  2010    10312545
       2020     9720846
인천광역시  2010     2758296
       2020     2947217
dtype: int64

In [90]:
male_tuple = [5111259,4732275,1773170,1668618,1390356,1476813,1255245,1198815,753648,734441,721780,720060]
male_tuple

[5111259,
 4732275,
 1773170,
 1668618,
 1390356,
 1476813,
 1255245,
 1198815,
 753648,
 734441,
 721780,
 720060]

In [91]:
korea_mdf = pd.DataFrame({'총인구수':population,'남자인구수':male_tuple})
korea_mdf

총인구수    남자인구수
서울특별시 2010  10312545  5111259
      2020   9720846  4732275
부산광역시 2010   2567910  1773170
      2020   3404423  1668618
인천광역시 2010   2758296  1390356
      2020   2947217  1476813
대구광역시 2010   2511676  1255245
      2020   2427954  1198815
대전광역시 2010   1503664   753648
      2020   1471040   734441
광주광역시 2010   1454636   721780
      2020   1455048   720060

In [93]:
korea_mdf['여자인구수']=korea_mdf['총인구수']-korea_mdf['남자인구수']
korea_mdf

총인구수    남자인구수    여자인구수
서울특별시 2010  10312545  5111259  5201286
      2020   9720846  4732275  4988571
부산광역시 2010   2567910  1773170   794740
      2020   3404423  1668618  1735805
인천광역시 2010   2758296  1390356  1367940
      2020   2947217  1476813  1470404
대구광역시 2010   2511676  1255245  1256431
      2020   2427954  1198815  1229139
대전광역시 2010   1503664   753648   750016
      2020   1471040   734441   736599
광주광역시 2010   1454636   721780   732856
      2020   1455048   720060   734988

In [94]:
ratio = korea_mdf['남자인구수']*100/korea_mdf['여자인구수']
ratio

서울특별시  2010     98.269140
       2020     94.862336
부산광역시  2010    223.113219
       2020     96.129346
인천광역시  2010    101.638668
       2020    100.435867
대구광역시  2010     99.905606
       2020     97.532907
대전광역시  2010    100.484256
       2020     99.707032
광주광역시  2010     98.488653
       2020     97.968946
dtype: float64

In [95]:
ratio.unstack()

2010        2020
광주광역시   98.488653   97.968946
대구광역시   99.905606   97.532907
대전광역시  100.484256   99.707032
부산광역시  223.113219   96.129346
서울특별시   98.269140   94.862336
인천광역시  101.638668  100.435867

In [96]:
korea_mdf['남여비율']=ratio
korea_mdf

총인구수    남자인구수    여자인구수        남여비율
서울특별시 2010  10312545  5111259  5201286   98.269140
      2020   9720846  4732275  4988571   94.862336
부산광역시 2010   2567910  1773170   794740  223.113219
      2020   3404423  1668618  1735805   96.129346
인천광역시 2010   2758296  1390356  1367940  101.638668
      2020   2947217  1476813  1470404  100.435867
대구광역시 2010   2511676  1255245  1256431   99.905606
      2020   2427954  1198815  1229139   97.532907
대전광역시 2010   1503664   753648   750016  100.484256
      2020   1471040   734441   736599   99.707032
광주광역시 2010   1454636   721780   732856   98.488653
      2020   1455048   720060   734988   97.968946

#### 다중 인덱스 생성

In [97]:
df=pd.DataFrame(np.random.rand(6,3),index=[['a','a','b','b','c','c'],[1,2,1,2,1,2]],columns=['c1','c2','c3'])
df

c1        c2        c3
a 1  0.241020  0.297705  0.269831
  2  0.030293  0.612567  0.062547
b 1  0.686940  0.804591  0.558144
  2  0.979049  0.982860  0.042528
c 1  0.382409  0.591190  0.188940
  2  0.109861  0.067546  0.286262

In [98]:
pd.MultiIndex.from_arrays([['a','a','b','b','c','c'],[1,2,1,2,1,2]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           )

In [100]:
pd.MultiIndex.from_tuples([('a',1),('a',2),('b',2),('c',1),('c',2)])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           )

In [101]:
pd.MultiIndex.from_product([['a','b','c'],[1,2]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           )

#### 인덱싱 및 슬라이싱

#### 다중 인덱스 재정렬

## 데이터 연산

### 연산자 범용 함수


#### add()

#### sub() / subtract()

#### mul() / multply()




#### truediv() /  div() / divide() / floordiv()

#### mod()

#### pow()

### 정렬(Sort)

### 순위(Ranking)


### 고성능 연산

## 데이터 결합

### Concat() / Append()

### 병합과 조인

## 데이터 집계와 그룹 연산

#### 집계 연산(Aggregation)


### GroupBy 연산

### 피벗 테이블(Pivot Table)


### 범주형(Categorical) 데이터


## 문자열 연산

#### 문자열 연산자

#### 기타 연산자


#### 정규표현식


## 시계열 처리

#### 시계열 데이터 구조


### 시계열 기본

### 주기와 오프셋


### 시프트(Shift)

### 시간대 처리

* 국제표준시(Coordinated Universal Time, UTC)를 기준으로 떨어진 거리만큼 오프셋으로 시간대 처리
* 전 세계의 시간대 정보를 모아놓은 올슨 데이터베이스를 활용한 라이브러리인 `pytz` 사용

### 기간과 기간 연산

### 리샘플링(Resampling)

* 리샘플링(Resampling): 시계열의 빈도 변환
* 다운샘플링(Down sampling): 상위 빈도 데이터를 하위 빈도 데이터로 집계
* 업샘플링(Up sampling): 하위 빈도 데이터를 상위 빈도 데이터로 집계

### 무빙 윈도우(Moving Window)

## 데이터 읽기 및 저장


### 텍스트 파일 읽기/쓰기

### 이진 데이터 파일 읽기/쓰기

## 데이터 정제

### 누락값 처리

* 대부분의 실제 데이터들은 정제되지 않고 누락값들이 존재
* 서로 다른 데이터들은 다른 형태의 결측을 가짐
* 결측 데이터는 `null`, `NaN`, `NA`로 표기

#### None: 파이썬 누락 데이터

#### NaN: 누락된 수치 데이터

#### Null 값 처리


### 중복 제거

### 값 치환

## 참고문헌

* Pandas 사이트: https://pandas.pydata.org/
* Jake VanderPlas, "Python Data Science Handbook", O'Reilly
* Wes Mckinney, "Python for Data Analysis", O'Reilly